services:
  - type: web
    name: java-training
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://java-training-db.ct8mgmqk627h.ap-southeast-1.rds.amazonaws.com:3306/java_training?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: Hoaanhdao123$%^&
      - key: JWT_SECRET
        value: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
      - key: PORT
        value: 8080
