spring:
  application:
    name: java_training

  datasource:
    url: jdbc:mysql://localhost:3306/java_training?useSSL=false&serverTimezone=UTC
    slaveUrl: jdbc:mysql://localhost:3306/java_training?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    connectionTimeOut: 20000
    minIdle: 20
    maxPoolSize: 100
    idleTimeout: 10000
    poolName: connection-pool
    autoCommit: false
    maxLifetime: 72000
    leakDetectionThreshold: 64800
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: sKZjtm=ZAw6g-LSLcIfW
    socket-timeout: 10s
    ssl:
      bundle:
        name: elasticsearch
    main:
      allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  batch:
    job:
      enabled: false

  thymeleaf:
    enabled: false
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  port: 8081

jwt:
  secret: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
  expiration: 3600000
